//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_9_NERI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IVANNEntities : DbContext
    {
        public IVANNEntities()
            : base("name=IVANNEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CabeceraFras> CabeceraFras { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<View_1_Pacientes_CE> View_1_Pacientes_CE { get; set; }
        public virtual DbSet<View_1_Pacientes_TEA> View_1_Pacientes_TEA { get; set; }
        public virtual DbSet<View_Caja> View_Caja { get; set; }
        public virtual DbSet<View_CE> View_CE { get; set; }
        public virtual DbSet<View_Pacientes_ALFA> View_Pacientes_ALFA { get; set; }
        public virtual DbSet<View_Pacientes_Alfabetico> View_Pacientes_Alfabetico { get; set; }
        public virtual DbSet<View_Remesa> View_Remesa { get; set; }
        public virtual DbSet<View_TEA> View_TEA { get; set; }
    
        public virtual ObjectResult<Nullable<System.DateTime>> FACTURASPORFECHA(Nullable<System.DateTime> fechaincio, Nullable<System.DateTime> fechafin)
        {
            var fechaincioParameter = fechaincio.HasValue ?
                new ObjectParameter("fechaincio", fechaincio) :
                new ObjectParameter("fechaincio", typeof(System.DateTime));
    
            var fechafinParameter = fechafin.HasValue ?
                new ObjectParameter("fechafin", fechafin) :
                new ObjectParameter("fechafin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("FACTURASPORFECHA", fechaincioParameter, fechafinParameter);
        }
    
        public virtual ObjectResult<Fras_By_Paciente_Result> Fras_By_Paciente()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Fras_By_Paciente_Result>("Fras_By_Paciente");
        }
    
        public virtual ObjectResult<Get_All_Pacientes_Result> Get_All_Pacientes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_All_Pacientes_Result>("Get_All_Pacientes");
        }
    
        public virtual ObjectResult<Get_Fras_By_Id_Result> Get_Fras_By_Id(Nullable<int> p1)
        {
            var p1Parameter = p1.HasValue ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Fras_By_Id_Result>("Get_Fras_By_Id", p1Parameter);
        }
    
        public virtual ObjectResult<string> Get_Ultima_Fra_TEA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Get_Ultima_Fra_TEA");
        }
    
        public virtual ObjectResult<Nullable<int>> Get_Ultimo_IDPACIENTE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Get_Ultimo_IDPACIENTE");
        }
    
        public virtual ObjectResult<GetAllFacturas_Result> GetAllFacturas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllFacturas_Result>("GetAllFacturas");
        }
    
        public virtual ObjectResult<GetPacienteBy_ID_Result> GetPacienteBy_ID(Nullable<int> p1)
        {
            var p1Parameter = p1.HasValue ?
                new ObjectParameter("p1", p1) :
                new ObjectParameter("p1", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPacienteBy_ID_Result>("GetPacienteBy_ID", p1Parameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> Ultima_Fra_CD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("Ultima_Fra_CD");
        }
    }
}
